seed:
  words:
    adjectives: >
      Auspicious,Awesome,Awful,Abandoned,Abashed,
      Abbreviated,
      Abducting,
      Aberrant,
      Abhorrent,
      Abiding,
      Bad,
      Bashful,
      Beautiful,
      Belligerent,
      Beneficial,
      Best,
      Big,
      Bitter,
      Bizarre,
      Black,
      Blue,
      Boring,
      Brainy,
      Bright,
      Broad,
      Broken,
      Busy,
      Barren,
      Barricaded,
      Basal,
      Basaltic,
      Based,
      Baseless,
      Basic,
      Bathyal,
      Batty,
      Bias,
      Calm,
      Capable,
      Careful,
      Careless,
      Caring,
      Cautious,
      Charming,
      Cheap,
      Cheerful,
      Chubby,
      Clean,
      Clever,
      Clumsy,
      Cold,
      Colorful,
      Comfortable,
      Concerned,
      Confused,
      Crowded,
      Cruel,
      Curious,
      Curly,
      Cute,
      Damaged,
      Dangerous,
      Dark,
      Deep,
      Defective,
      Delicate,
      Delicious,
      Depressed,
      Determined,
      Different,
      Dirty,
      Disgusting,
      Dry,
      Dusty,
      Daft,
      Daily,
      Dainty,
      Damn,
      Damning,
      Damp,
      Darned,
      Dauntless,
      Daylong,
      Early,
      Educated,
      Efficient,
      Elderly,
      Elegant,
      Embarrassed,
      Empty,
      Encouraging,
      Enthusiastic,
      Excellent,
      Exciting,
      Expensive,
      Fabulous,
      Fair,
      Faithful,
      Famous,
      Fancy,
      Fantastic,
      Fast,
      Fearful,
      Fearless,
      Fertile,
      Filthy,
      Foolish,
      Forgetful,
      Friendly,
      Funny,
      Gentle,
      Glamorous,
      Glorious,
      Gorgeous,
      Graceful,
      Grateful,
      Great,
      Greedy,
      Green,
      Handsome,
      Happy,
      Harsh,
      Healthy,
      Heavy,
      Helpful,
      Hilarious,
      Historical,
      Horrible,
      Hot,
      Huge,
      Humorous,
      Hungry,
      Ignorant,
      Illegal,
      Imaginary,
      Impolite,
      Important,
      Impossible,
      Innocent,
      Intelligent,
      Interesting,
      Jealous,
      Jolly,
      Juicy,
      Juvenile,
      Kind,
      Large,
      Legal,
      Light,
      Literate,
      Little,
      Lively,
      Lonely,
      Loud,
      Lovely,
      Lucky,
      Macho,
      Magical,
      Magnificent,
      Massive,
      Mature,
      Mean,
      Messy,
      Modern,
      Narrow,
      Nasty,
      Naughty,
      Nervous,
      New,
      Noisy,
      Nutritious,
      Obedient,
      Obese,
      Obnoxious,
      Old,
      Overconfident,
      Peaceful,
      Pink,
      Polite,
      Poor,
      Powerful,
      Precious,
      Pretty,
      Proud,
      Quick,
      Quiet,
      Rapid,
      Rare,
      Red,
      Remarkable,
      Responsible,
      Rich,
      Romantic,
      Royal,
      Rude,
      Scintillating,
      Secretive,
      Selfish,
      Serious,
      Sharp,
      Shiny,
      Shocking,
      Short,
      Shy,
      Silly,
      Sincere,
      Skinny,
      Slim,
      Slow,
      Small,
      Soft,
      Spicy,
      Spiritual,
      Splendid,
      Strong,
      Successful,
      Sweet,
      Talented,
      Tall,
      Tense,
      Terrible,
      Terrific,
      Thick,
      Thin,
      Tiny,
      Tactful,
      Tailor-made,
      Tangible,
      Tasteful,
      Tasty,
      Teachable,
      Teeming,
      Temperate,
      Tenable,
      Tenacious,
      Tender,
      Tender-hearted,
      Terrific,
      Testimonial,
      Thankful,
      Therapeutic,
      Thorough,
      Thoughtful,
      Ugly,
      Unique,
      Untidy,
      Upset,
      Victorious,
      Violent,
      Vulgar,
      Warm,
      Weak,
      Wealthy,
      Wide,
      Wise,
      Witty,
      Wonderful,
      Worried,
      Young,
      Youthful,
      Zealous
    verbs: >
      watering,cataloging,hunting,wanting,holding,taping,integrating,worrying,loving,spending,fitting,bating,risking,normalizing,restructuring,costing,programming,touching,towing,altering,marketing,yelling,crushing,beholding,agreeing,fencing,sparkling,wiping,sparking,slaying,
      copying,melting,appraising,complaining,leading,telling,crashing,subtracting,normalizing,grabbing,wrecking,thanking,forming,answering,overhearing,wriggling,ringing,admitting,bruising,making,pumping,melting,bumping,dragging,consisting,accepting,dropping,smelling,recognizing,facing,
      deciding,deserting,riding,ensuring,frightening,shading,flapping,washing,completing,heaping,snoring,draining,clothing,detailing,initiating,dispensing,diagnosing,paddling,singing,promising,handling,planing,separating,thriving,shrinking,scrubbing,confusing,spotting,scattering,noticing,
      upgrading,piloting,estimating,showing,reigning,folding,contracting,blushing,broadcasting,speaking,slipping,squashing,pecking,hanging,returning,receiving,landing,injecting,fleeing,cheering,sniffing,sleeping,clinging,breeding,searching,carving,meaning,attaching,affording,nesting,undergoing,
      passing,entertaining,longing,enjoying,fighting,wrestling,unfastening,drawing,supposing,knotting,greasing,producing,spinning,squashing,asking,projecting,enduring,adopting,fancying,conducting,conceiving,guessing,mating,overthrowing,regulating,determining,bearing,devising,abiding,piloting,hearing,
      rhyming,retrieving,servicing,integrating,preaching,rubbing,clarifying
    nouns: >
      people,art,world,information,map,family,government,health,system,computer,meat,years,music,person,method,data,food,theories,laws,birds,problem,software,control,knowledge,power,ability,economics,love,internet,television,
      science,library,nature,fact,product,ideas,temperature,investment,areas,societies,activities,story,industry,media,thing,oven,community,definition,safety,quality,development,language,management,player,variety,video,week,security,country,exam,movie,organization,equipment,physics,analysis,policy,
      series,thought,basis,boyfriends,directions,strategy,technology,army,camera,freedom,paper,environment,child,instance,month,truth,marketing,university,writing,article,department,difference,goal,news,audience,fishing,growth,income,marriage,user,combination,failure,meaning,medicine,philosophy,teacher,
      communication,night,chemistry,disease,disk,energy,nation,road,role,soup,advertising,location,success,addition,apartment,education,math,moment,painting,politics,attention,decision,event,property,shopping,student,wood,competition,distribution,entertainment,office,population,president,unit,category,
      cigarette,context,introduction,opportunity,performance,driver,flight,length,magazine,newspaper,relationship,teaching,cell,dealer,finding,lake,member,message,phone,scene,appearance,association,concept,customer,death,discussion,housing,inflation,insurance,mood,woman,advice,blood,effort,expression,importance,
      opinion,payment,reality,responsibility,situation,skill,statement,wealth,application,city,county,depth,estate,foundation,grandmother,heart,perspective,photo,recipe,studio,topic,collection,depression,imagination,passion,percentage,resource,setting,ad,agency,college,connection,criticism,debt,description,
      memory,patience,secretary,solution,administration,aspect,attitude,director,personality,psychology,recommendation,response,selection,storage,version,alcohol,argument,complaint,contract,emphasis,highway,loss,membership,possession,preparation,steak,union,agreement,cancer,currency,employment,engineering,entry,
      interaction,mixture,preference,region,republic,tradition,virus,actor,classroom,delivery,device,difficulty,drama,election,engine,football,guidance,hotel,owner,priority,protection,suggestion,tension,variation,anxiety,atmosphere,awareness,bath,bread,candidate,climate,comparison,confusion,construction,elevator,emotion,
      employee,employer,guest,height,leadership,mall,manager,operation,recording,sample,transportation,charity,cousin,disaster,editor,efficiency,excitement,extent,feedback,guitar,homework,leader,mom,outcome,permission,presentation,promotion,reflection,refrigerator,resolution,revenue,session,singer,tennis,basket,bonus,cabinet,
      childhood,church,clothes,coffee,dinner,drawing,hair,hearing,initiative,judgment,lab,measurement,mode,mud,orange,poetry,police,possibility,procedure,queen,ratio,relation,restaurant,satisfaction,sector,signature,significance,song,tooth,town,vehicle,volume,wife,accident,airport,appointment,arrival,assumption,baseball,chapter,
      committee,conversation,database,enthusiasm,error,explanation,farmer,gate,girl,hall,historian,hospital,injury,instruction,maintenance,manufacturer,meal,perception,pie,poem,presence,proposal,reception,replacement,revolution,river,son,speech,tea,village,warning,winner,worker,writer,assistance,breath,buyer,chest,chocolate,conclusion,
      contribution,cookie,courage,dad,desk,drawer,establishment,examination,garbage,grocery,honey,impression,improvement,independence,insect,inspection,inspector,king,ladder,menu,penalty,piano,potato,profession,professor,quantity,reaction,requirement,salad,sister,supermarket,tongue,weakness,wedding,affair,ambition,analyst,apple,assignment,
      assistant,bathroom,bedroom,beer,birthday,celebration,championship,cheek,client,consequence,departure,diamond,dirt,ear,fortune,friendship,funeral,gene,girlfriend,hat,indication,intention,lady,midnight,negotiation,obligation,passenger,pizza,platform,poet,pollution,recognition,reputation,shirt,sir,speaker,stranger,surgery,sympathy,tale,throat,trainer,uncle,youth
